steps:
- id: make-dev
  name: gcr.io/kaniko-project/executor
  args:
  - --destination=gcr.io/${PROJECT_ID}/app:development
  - --cache=true
  - --skip-unused-stages=true
  - --target=development
  - --use-new-run
- id: make-prod
  waitFor: ["-"]
  name: gcr.io/kaniko-project/executor
  args:
  - --destination=gcr.io/${PROJECT_ID}/app:production
  - --cache=true
  - --skip-unused-stages=true
  - --target=production
  - --use-new-run
- id: terraform-init
  waitFor: ["make-dev"]
  name: gcr.io/${PROJECT_ID}/app:development
  dir: infra/app
  args:
  - terraform
  - init
  - "-backend-config=bucket=${PROJECT_ID}-state"
  - "-input=false"
- id: terraform-apply
  waitFor: ["terraform-init"]
  name: gcr.io/${PROJECT_ID}/app:development
  dir: infra/app
  env:
  - TF_VAR_deploy_gcp_project_id=${PROJECT_ID}
  args: ["terraform", "apply", "-input=false", "-auto-approve"]
- id: cleanup
  waitFor: ["make-dev", "make-prod"]
  name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
  args:
  - bash
  - -c
  - |
    for digest in $$(gcloud container images list-tags gcr.io/${PROJECT_ID}/app --filter "NOT tags:*" --format="get(digest)")
    do
    gcloud container images delete gcr.io/${PROJECT_ID}/app@$${digest} --quiet
    done
