version: "3.7"
services:
  gpodder:
    build: ./gpodder
    environment:
      GCP_PROJECT_ID: qcmautomator
      APP_NAME: gpodder
      GOOGLE_APPLICATION_CREDENTIALS: /app/creds.json
    volumes:
    - "./gpodder:/app"
  stocks:
    build: ./stocks
    environment:
      GCP_PROJECT_ID: qcmautomator
      APP_NAME: stocks
      GOOGLE_APPLICATION_CREDENTIALS: /app/creds.json
    volumes:
    - "./stocks:/app"
