version: "3.7"
services:
  app:
    build:
      context: .
      target: development
    environment:
      TF_VAR_gcp_billing_account: ${TF_VAR_gcp_billing_account}
      TF_VAR_gcp_project_id: ${TF_VAR_gcp_project_id}
    volumes:
    - ".:/usr/src/app"
    - "~/.config/gcloud:/root/.config/gcloud"
    - "./config:/etc/app"
