version: "3.7"
services:
  stocks:
    build: ./stocks
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/creds.json
      GCP_PROJECT_ID: qcmautomator
      APP_NAME: stocks
    ports:
    - "8001:8080"
    volumes:
    - "./stocks:/app"
