substitutions:
  _APP_NAME: stocks

steps:
# Use docker cache
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - 'docker pull gcr.io/$PROJECT_ID/$_APP_NAME:latest || exit 0'

# Build the app
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_APP_NAME', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$_APP_NAME']

# Deploy it
- name: 'gcr.io/$PROJECT_ID/terraform'
  args:
  - init
  - '-input=false'
  - '-backend-config=bucket=qcmautomator_tfstate'
  - '-backend-config=prefix=$_APP_NAME'
- name: 'gcr.io/${PROJECT_ID}/terraform'
  args: ['apply', '-auto-approve']
  env:
  - 'TF_VAR_app_name=$_APP_NAME'
  - 'TF_VAR_gcp_project_id=$PROJECT_ID'
