substitutions:
  _APP_NAME: stocks

steps:
- name: "gcr.io/kaniko-project/executor"
  args:
  - --destination=gcr.io/$PROJECT_ID/$_APP_NAME
  - --cache=true

# Deploy it
- name: 'gcr.io/$PROJECT_ID/terraform'
  entrypoint: './deploy.sh'
  args: [$PROJECT_ID, $_APP_NAME]
