tags: ["watching"]

logsBucket: gs://${PROJECT_ID}-build-logs
serviceAccount: projects/${PROJECT_ID}/serviceAccounts/watching-executor@${PROJECT_ID}.iam.gserviceaccount.com
options:
  logging: GCS_ONLY
  volumes:
  - name: secrets
    path: /etc/app/

steps:
- id: get-secrets
  name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
  args:
  - gsutil
  - cp
  - gs://${PROJECT_ID}-secrets/watching/*
  - /etc/app/
- id: run-episodes
  name: gcr.io/${PROJECT_ID}/app
  dir: /usr/src/app
  args:
  - python
  - run.py
  - watching
  - load-episodes
- id: run-movies
  name: gcr.io/${PROJECT_ID}/app
  dir: /usr/src/app
  args:
  - python
  - run.py
  - watching
  - load-movies
- id: update-token
  name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
  args:
  - gsutil
  - cp
  - /etc/app/trakt_refresh_token
  - gs://${PROJECT_ID}-secrets/watching/trakt_refresh_token
